Revert "use archaic UT for tf-vcenter*manager"
This reverts commit f355e5b16983ff28e6e620f20f47d5f02dc4383e.

Seeing error during `git fetch`:
OSError: [Errno 2] No such file or directory: '/home/centos/src/review.opencontrail.org/tungstenfabric/tf-vcenter-manager'

Change-Id: I4afba1444af856a028a6cf32d8ca3b46fb08696c